(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "[cl-struct-package-desc rainbow-mode (0 9) Colorize color names in buffers nil single gnu nil ((:url . http://elpa.gnu.org/packages/rainbow-mode.html)) nil]")
(depends-on "ag")
(depends-on "auto-complete")
(depends-on "dash-at-point")
(depends-on "enh-ruby-mode")
(depends-on "flyspell-lazy")
(depends-on "highlight-indentation")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "rinari")
(depends-on "robe")
(depends-on "smartparens")
(depends-on "textmate")
(depends-on "web-mode")
(depends-on "yasnippet")